name: documentation


on: 
  workflow_dispatch:
  workflow_run:
    workflows: ["Deploy Package Workflow"]
    types:
      - completed

permissions:
  contents: write

jobs:
  deploy_local_template:
    uses: anglisanosa/ci_cd_templates/.github/workflows/gh_pages_documentation.yml@main
    secrets:
      githubtoken: ${{ secrets.GITHUB_TOKEN }}