name: Package Test and Coverage Workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  issues: read
  checks: write
  pull-requests: write

jobs:
  test_and_coverage:
    uses: anglisanosa/ci_cd_templates/.github/workflows/test_and_coverage.yml@v1
    with:
      python_environments: '[3.8, 3.9]'